mysite/libra/urls.py
from django.urls import path
from . import views

app_name = 'libra'
urlpatterns=[
    path('addBook/',views.addBook,name='addBook'),
    path('delBook/<int:book_id>', views.deleteBook, name='delBook'),
    path('updateBook/',views.updateBook, name='updateBook'),
    path('detail/', views.detail, name='detail'),
    path('', views.index, name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('lib/detail',include('libra.urls')),
    path('libra/',include('libra.urls')),
    path('admin/', admin.site.urls),
]

mysite/libra/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name=models.CharField(max_length=200)
    author=models.CharField(max_length=100)
    pub_house=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')

mysite/libra/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponseRedirect
# Create your views here.
def index(request):
    return HttpResponse("hello world!")

def detail(request):
    book_list=Book.objects.order_by('pub_date')[:5]
    context={'book_list': book_list}
    return render(request,'lib/detail.html',context)

def addBook(request):
    if request.method == 'POST':
        temp_name=request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
    temp_book.save()
    #重定向
    return HttpResponseRedirect(reverse('libra:detail'))

def deleteBook(request,book_id):
    book_ID=book_id
    Book.objects.filter(id=book_ID).delete()
    return HttpResponseRedirect(reverse('libra:detail'))

def updateBook(request):
    if request.method == 'POST':
        temp_name=request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']
    if Book.objects.filter(name=temp_name):
        Book.objects.filter(name=temp_name).delete()
        temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
        temp_book.save()
        return HttpResponseRedirect(reverse('libra:detail'))

mysite/libra/templates/lib/detail.html
<h1>Book List</h1>
<table>
    <tr>
        <td>书名</td>
        <td>作者</td>
        <td>出版社</td>
        <td>出版时间</td>
    </tr>
{% for book in book_list.all %}
    <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>
        <td><a href="{% url 'libra:delBook' book.id %}">删除</a></td>
    </tr>
{% endfor %}
</table>
<form action="{% url 'libra:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>书名：</span><input type="text"  name="name"></p>
    <p><span>作者：</span><input type="text"  name="author"></p>
    <p><span>出版社：</span><input type="text"  name="pub_house"></p>
    <input type="submit" value="添加">
</form>

<form action="{% url 'libra:updateBook' %}" method="post" name="updateBook">
    {% csrf_token %}
    <p><span>书名：</span><input type="text"  name="name"></p>
    <p><span>作者：</span><input type="text"  name="author"></p>
    <p><span>出版社：</span><input type="text"  name="pub_house"></p>
    <input type="submit" value="更新">
</form>